import "./Experiences.css";

function Experiences() {
    return (
        <section id="experiences" className="section">
        <h2>Experiences</h2>

            <div className="experience-timeline">

                <article className="experience-item">
                    <div className="experience-dot"></div>

                    <div className="experience-card">
                        <div className="experience-header">
                            <div>
                                <h3>Research Student</h3>
                                <h4>LRE</h4>
                            </div>

                            <span className="experience-date">
                                Feb 2026 - Jul 2026
                            </span>
                        </div>

                        <p>
                           Student researcher within the system security team.<br />
                           My primary task is to optimize the active S-box minimization 
                           step of the differential cryptanalysis tool TAGADA.<br />
                           To achieve this, I am implementing multithreaded 
                           dynamic programming algorithms in C++. 
                           I then generalize them to handle the encryption 
                           operations generated by the tool, which are 
                           represented as a graph in JSON format.
                        </p>

                        <ul className="experience-tasks">
                        </ul>

                        <div className="experience-tags">
                            <span>C++</span>
                            <span>Docker</span>
                            <span>Git</span>
                            <span>Benchmarking</span>
                            <span>Academic Research</span>

                        </div>
                    </div>
                </article>

                <article className="experience-item">
                    <div className="experience-dot"></div>

                    <div className="experience-card">
                        <div className="experience-header">
                            <div>
                                <h3>Teaching Assistant</h3>
                                <h4>EPITA</h4>
                            </div>

                            <span className="experience-date">
                                Aug 2025 - Jul 2026
                            </span>
                        </div>

                        <p>
                            Programming assistant for first-year students in 
                            EPITA's preparatory cycle.<br />
                            My primary responsibilities involve providing daily
                            guidance to students as they learn C, Python, 
                            and Git, and helping them get up to speed with the 
                            Linux environment (NixOS).<br />
                            Additionally, I assist in reviewing assignments and
                            tests for weekly practical sessions via GitLab, as 
                            well as grading the students' work.<br />
                            These tasks allow me to practice using the 
                            C language and the Criterion framework on a daily 
                            basis, while also honing my adaptability and 
                            problem-solving skills.
                        </p>

                        <div className="experience-tags">
                            <span>C</span>
                            <span>Python</span>
                            <span>Ocaml</span>
                            <span>Teaching</span>
                        </div>
                    </div>
                </article>

                <article className="experience-item">
                    <div className="experience-dot"></div>

                    <div className="experience-card">
                        <div className="experience-header">
                            <div>
                                <h3>Teaching Assistant</h3>
                                <h4>SupBiotech</h4>
                            </div>

                            <span className="experience-date">
                                Sep 2025 - Jun 2026
                            </span>
                        </div>

                        <p>
                            Assisting preparatory class students during 
                            programming practical sessions.<br />
                            My primary role is to support students during Python
                            practicals, helping them with both language-specific
                            details and algorithmic concepts.
                        </p>

                        <div className="experience-tags">
                            <span>Algorithm</span>
                            <span>Python</span>
                        </div>
                    </div>
                </article>
            </div>
        </section>
    );
}

export default Experiences;
